repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
      # Doku: https://pre-commit.com/hooks.html
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
        args: ['--assume-in-merge']
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=auto']  # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows
      - id: no-commit-to-branch
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

    # Ruff replaces black, flake8, autoflake, isort and more
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: 'v0.9.1'
      hooks:
        - id: ruff
        - id: ruff-format
          args: [--config, ./pyproject.toml]
