name: Test suite

on: push

jobs:
  type-hint:
    name: type hinting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.0"
          python-version-file: ".python-version"
          enable-cache: true
      - name: Install project
        run: uv sync --locked --group test
      - name: Run type
        run: uvx ty check

  lint:
    name: linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.0"
          python-version-file: ".python-version"
          enable-cache: true
      - name: Run lint
        run: uvx ruff==0.9.1 check

  tests:
    name: tests
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
        exclude:
          - os: "ubuntu-latest"
            python-version: "3.12"
      fail-fast: false
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.0"
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - name: Install project
        run: uv sync --locked --group test
      - name: Run tests
        run: uv run pytest tests

  coverage:
    name: coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.0"
          python-version-file: ".python-version"
          enable-cache: true
      - name: Install project
        run: uv sync --locked --group test
      - name: Run tests
        run: uv run coverage run -m pytest tests --junitxml=junit.xml -o junit_family=legacy
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
